
export const data = [
  {
    id : 0,
    title : "1 Book",
    author : "Anonymous",
    initial: "X",
    description : "Description 1 ",
    date : "27 December 2018",
    linkPdf : "http://www.orimi.com/pdf-test.pdf",
    like : true,
    tags : ["awesome","funny"],
    language : "English",
    canEdit : false,
  },

  {
    id : 1,
    title : "2 Book",
    author : "Anonymous",
    initial: "X",
    description : "Description 2 ",
    date : "27 December 2018",
    linkPdf : "http://www.orimi.com/pdf-test.pdf",
    like : true,
    tags : ["awesome","funny"],
    language : "English",
    canEdit : false,
  },

  {
    id : 3,
    title : "3 Book",
    author : "Anonymous",
    initial: "X",
    description : "Description 3",
    date : "27 December 2018",
    linkPdf : "http://www.orimi.com/pdf-test.pdf",
    like : true,
    tags : ["awesome","funny"],
    language : "English",
    canEdit : false,
  },

  {
    id : 4,
    title : "4 Book",
    author : "Anonymous",
    initial: "X",
    description : "Description 4 ",
    date : "27 December 2018",
    linkPdf : "http://www.orimi.com/pdf-test.pdf",
    like : true,
    tags : ["awesome","funny"],
    language : "English",
    canEdit : false,
  },

  {
    id : 5,
    title : "5 Book",
    author : "Anonymous",
    initial: "X",
    description : "Description 5 ",
    date : "27 December 2018",
    linkPdf : "http://www.orimi.com/pdf-test.pdf",
    like : true,
    tags : ["awesome","funny"],
    language : "English",
    canEdit : false,
  },

  {
    id : 6,
    title : "8 Book",
    author : "Anonymous",
    initial: "X",
    description : "Description 6 ",
    date : "27 December 2018",
    linkPdf : "http://www.orimi.com/pdf-test.pdf",
    like : true,
    tags : ["awesome","funny"],
    language : "English",
    canEdit : false,
  },


  ];